name: molgan_win
channels:
  - rdkit
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12=py37_0
  - argcomplete=1.12.3=pyhd3eb1b0_0
  - arrow=0.13.1=py37_0
  - astroid=2.6.6=py37haa95532_0
  - async_generator=1.10=py37h28b3542_0
  - atomicwrites=1.4.0=py_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - autopep8=1.6.0=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bcrypt=3.2.0=py37he774522_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - black=19.10b0=py_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.2=py37h2a96729_1
  - brotlipy=0.7.0=py37h2bbff1b_1003
  - ca-certificates=2021.10.26=haa95532_2
  - cairo=1.14.12=hf171d8a_3
  - certifi=2021.10.8=py37haa95532_2
  - cffi=1.15.0=py37h2bbff1b_0
  - chardet=4.0.0=py37haa95532_1003
  - click=8.0.3=pyhd3eb1b0_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - cookiecutter=1.7.2=pyhd3eb1b0_0
  - cryptography=36.0.0=py37h21b164f_0
  - cudatoolkit=11.3.1=h280eb24_10
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.5.1=py37hd77b12b_0
  - decorator=5.1.0=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - docutils=0.17.1=py37haa95532_1
  - entrypoints=0.3=py37_0
  - flake8=3.9.2=pyhd3eb1b0_0
  - freetype=2.10.4=hd328e21_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - idna=3.3=pyhd3eb1b0_0
  - imagesize=1.3.0=pyhd3eb1b0_0
  - importlib_metadata=4.8.2=hd3eb1b0_0
  - inflection=0.5.1=py37haa95532_0
  - intel-openmp=2021.4.0=haa95532_3556
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipykernel=6.4.1=py37haa95532_1
  - ipython=7.29.0=py37hd4e2768_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - isort=5.9.3=pyhd3eb1b0_0
  - jedi=0.18.0=py37haa95532_1
  - jinja2=2.11.3=pyhd3eb1b0_0
  - jinja2-time=0.2.0=pyhd3eb1b0_2
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9d=h2bbff1b_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_core=4.9.1=py37haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - keyring=23.4.0=py37haa95532_0
  - kiwisolver=1.3.1=py37hd77b12b_0
  - lazy-object-proxy=1.6.0=py37h2bbff1b_0
  - libboost=1.67.0=hd9e427e_4
  - libpng=1.6.37=h2a8f88b_0
  - libspatialindex=1.9.3=h6c2663c_0
  - libtiff=4.2.0=hd0e1b90_0
  - libuv=1.40.0=he774522_0
  - libwebp=1.2.0=h2bbff1b_0
  - lz4-c=1.9.3=h2bbff1b_1
  - markupsafe=1.1.1=py37hfa6e2cd_1
  - matplotlib=3.2.2=1
  - matplotlib-base=3.2.2=py37h64f37c6_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37hfa6e2cd_1001
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py37h2bbff1b_0
  - mkl_fft=1.3.1=py37h277e83a_0
  - mkl_random=1.2.2=py37hf11a4ad_0
  - mypy_extensions=0.4.3=py37haa95532_1
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py37haa95532_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - numexpr=2.8.1=py37hb80d3ca_0
  - numpy=1.21.2=py37hfca59bb_0
  - numpy-base=1.21.2=py37h0829f74_0
  - numpydoc=1.1.0=pyhd3eb1b0_1
  - olefile=0.46=py37_0
  - openssl=1.1.1m=h2bbff1b_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.3.5=py37h6214cd6_0
  - pandocfilters=1.4.3=py37haa95532_1
  - paramiko=2.8.1=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pathspec=0.7.0=py_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.4.0=py37hd45dc43_0
  - pip=21.2.4=py37haa95532_0
  - pixman=0.40.0=h2bbff1b_1
  - pluggy=1.0.0=py37haa95532_0
  - poyo=0.5.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - psutil=5.8.0=py37h2bbff1b_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - py-boost=1.67.0=py37h8300f20_4
  - pycodestyle=2.7.0=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pydocstyle=6.1.1=pyhd3eb1b0_0
  - pyflakes=2.3.1=pyhd3eb1b0_0
  - pygments=2.10.0=pyhd3eb1b0_0
  - pylint=2.9.6=py37haa95532_1
  - pyls-spyder=0.4.0=pyhd3eb1b0_0
  - pynacl=1.4.0=py37h62dcd97_1
  - pyopenssl=21.0.0=pyhd3eb1b0_1
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py37h6538335_2
  - pyrsistent=0.18.0=py37h196d8e1_0
  - pysocks=1.7.1=py37_1
  - python=3.7.10=h6244533_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-lsp-black=1.0.0=pyhd3eb1b0_0
  - python-lsp-jsonrpc=1.0.0=pyhd3eb1b0_0
  - python-lsp-server=1.2.4=pyhd3eb1b0_0
  - python-slugify=5.0.2=pyhd3eb1b0_0
  - pytorch=1.10.2=py3.7_cuda11.3_cudnn8_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd3eb1b0_0
  - pywin32=302=py37h827c3e9_1
  - pywin32-ctypes=0.2.0=py37_1001
  - pyyaml=6.0=py37h2bbff1b_1
  - pyzmq=22.3.0=py37hd77b12b_2
  - qdarkstyle=3.0.2=pyhd3eb1b0_0
  - qstylizer=0.1.10=pyhd3eb1b0_0
  - qt=5.9.7=vc14h73c81de_0
  - qtawesome=1.0.3=pyhd3eb1b0_0
  - qtconsole=5.1.1=pyhd3eb1b0_0
  - qtpy=1.10.0=pyhd3eb1b0_0
  - rdkit=2020.09.1.0=py37h3d1ada6_1
  - regex=2021.8.3=py37h2bbff1b_0
  - requests=2.27.1=pyhd3eb1b0_0
  - rope=0.21.1=pyhd3eb1b0_0
  - rtree=0.9.7=py37h2eaa2aa_1
  - scikit-learn=0.23.2=py37h47e9c7a_0
  - scipy=1.7.3=py37h0a974cb_0
  - setuptools=58.0.4=py37haa95532_0
  - sip=4.19.8=py37h6538335_0
  - six=1.16.0=pyhd3eb1b0_0
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - sphinx=4.2.0=pyhd3eb1b0_1
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - spyder=5.1.5=py37haa95532_1
  - spyder-kernels=2.1.3=py37haa95532_0
  - sqlite=3.37.0=h2bbff1b_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - textdistance=4.2.1=pyhd3eb1b0_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tinycss=0.4=pyhd3eb1b0_1002
  - tk=8.6.11=h2bbff1b_0
  - toml=0.10.2=pyhd3eb1b0_0
  - torchaudio=0.10.2=py37_cu113
  - torchvision=0.11.3=py37_cu113
  - tornado=6.1=py37h2bbff1b_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typed-ast=1.4.3=py37h2bbff1b_1
  - typing-extensions=3.10.0.2=hd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - ujson=4.0.2=py37hd77b12b_0
  - unidecode=1.2.0=pyhd3eb1b0_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - watchdog=2.1.6=py37haa95532_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py37_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - whichcraft=0.6.1=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py37haa95532_0
  - wincertstore=0.2=py37haa95532_2
  - xz=5.2.5=h62dcd97_0
  - yaml=0.2.5=he774522_0
  - yapf=0.31.0=pyhd3eb1b0_0
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.11=h8cc25b3_4
  - zstd=1.4.9=h19a0ad4_0
  - pip:
    - absl-py==1.0.0
    - appdirs==1.4.4
    - astor==0.8.1
    - astunparse==1.6.3
    - autograd==1.3
    - autoray==0.2.5
    - cached-property==1.5.2
    - cachetools==4.2.4
    - charset-normalizer==2.0.10
    - flatbuffers==2.0
    - frechetdist==0.6
    - future==0.18.2
    - gast==0.2.2
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.43.0
    - h5py==3.6.0
    - importlib-metadata==4.10.0
    - keras==2.7.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - libclang==13.0.0
    - markdown==3.3.6
    - networkx==2.6.3
    - ninja==1.10.2.3
    - oauthlib==3.1.1
    - opt-einsum==3.3.0
    - pbr==5.8.0
    - pennylane==0.20.0
    - pennylane-lightning==0.20.2
    - protobuf==3.19.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pysmiles==1.0.1
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - semantic-version==2.6.0
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.7.0
    - tensorflow-estimator==2.7.0
    - tensorflow-gpu==1.15.0
    - tensorflow-io-gcs-filesystem==0.23.1
    - termcolor==1.1.0
    - tqdm==4.62.3
    - urllib3==1.26.8
    - werkzeug==2.0.2
    - wrapt==1.13.3
prefix: C:\Users\yunly\anaconda3\envs\molgan_win
